---
- name: process | Set download facts
  include_tasks: set_download_facts.yml
  tags: facts

- name: process | Download files / images
  include_tasks: "{{ include_file }}"
  vars:
    include_file: "download_{% if download.container %}container{% else %}file{% endif %}.yml"
  when:
    - (download_run_once and inventory_hostname == download_delegate) or (group_names | intersect(download.groups) | length)

- name: process | Sync files / images from ansible host to nodes
  include_tasks: sync.yml
  when:
    - download_run_once
    - group_names | intersect(download.groups) | length
    - not (inventory_hostname == download_delegate)
