---
- block:

  #############
  ## Pre-Sync

  - name: sync | Create dest directory on node (File)
    file:
      path: "{{ download.dest | dirname }}"
      owner: "{{ download.owner | default(omit) }}"
      mode: 0755
      state: directory
      recurse: yes
    when: download.file


  #############
  ## Sync

  - name: sync | Upload file/image to node
    synchronize:
      src: "{{ download_facts.cache_path }}"
      dest: "{{ download_facts.dest }}"
      use_ssh_args: "{{ has_bastion | default(false) }}"
      mode: push
    become: true
    register: get_task
    until: get_task is succeeded
    retries: 4
    delay: "{{ retry_stagger | random + 3 }}"
    when:
    - ansible_os_family not in ["CoreOS", "Container Linux by CoreOS"]


  #############
  ## Post-Sync

  - name: sync | Set mode and owner (File)
    file:
      path: "{{ download.dest }}"
      mode: "{{ download.mode | default(omit) }}"
      owner: "{{ download.owner | default(omit) }}"
    when: download.file

  - name: sync | Extract file archives (File)
    include_tasks: "extract_file.yml"
    when: download.file

  - name: sync | Load container image into docker (Container)
    shell: "{{ docker_bin_dir }}/docker load < {{ download_facts.dest }}"
    when:
    - ansible_os_family not in ["CoreOS", "Container Linux by CoreOS"]
    - download.container

  - name: sync | Remove container image from cache (Container)
    file:
      state: absent
      path: "{{ download_facts.dest }}"
    when:
    - not download_keep_remote_cache
    - ansible_os_family not in ["CoreOS", "Container Linux by CoreOS"]
    - download.container

  tags:
  - upload
